# Generated by Django 4.1.3 on 2022-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='winner',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
